In [13]:
from bcb import Expectativas
def dados_expectativas_focus(
    indicador="IPCA",
    tipo_expectativa="ExpectativaMercadoMensais",
    data_inicio="2000-01-01",
    
):
    # End point
    em = Expectativas()
    ep = em.get_endpoint(tipo_expectativa)
    # Dados do IPCA
    atributos_necessarios = ["Indicador", "Data", "Media", "Mediana", "DataReferencia", "baseCalculo"]
    if all(hasattr(ep, attr) for attr in atributos_necessarios):
        ipca_expec = (
            ep.query()
            .filter(ep.Indicador == indicador)
            .filter(ep.Data >= data_inicio)
            .filter(ep.baseCalculo == 0)
            .select(
                ep.Indicador,
                ep.Data,
                ep.Media,
                ep.Mediana,
                ep.DataReferencia,
                ep.baseCalculo,
            )
            .collect()
        )
        return ipca_expec
    else:
        print("Indicador não encontrado")

In [14]:
dados_expectativas_focus()

       Indicador       Data DataReferencia   Media  Mediana  baseCalculo
0           IPCA 2024-08-16        08/2026  0.1631   0.1750            0
1           IPCA 2024-08-16        07/2026  0.1953   0.1947            0
2           IPCA 2024-08-16        06/2026  0.2120   0.2000            0
3           IPCA 2024-08-16        05/2026  0.2593   0.2500            0
4           IPCA 2024-08-16        04/2026  0.3387   0.3300            0
...          ...        ...            ...     ...      ...          ...
103328      IPCA 2000-01-05        04/2000  0.6100   0.6000            0
103329      IPCA 2000-01-04        05/2000  0.6000   0.5500            0
103330      IPCA 2000-01-04        04/2000  0.6000   0.6000            0
103331      IPCA 2000-01-03        05/2000  0.6100   0.5800            0
103332      IPCA 2000-01-03        04/2000  0.6000   0.6000            0

[103333 rows x 6 columns]

In [20]:
def dados_expectativas_focus(
    indicador="IPCA",
    tipo_expectativa="ExpectativaMercadoMensais",
    data_inicio="2000-01-01",
):
    # End point
    em = Expectativas()
    ep = em.get_endpoint(tipo_expectativa)

    # Dados do IPCA
    ipca_expec = (
        ep.query()
        .filter(getattr(ep, 'Indicador', None) == indicador)
        .filter(getattr(ep, 'Data', None) >= data_inicio)
        .filter(getattr(ep, 'baseCalculo', None) == 0)
        .select(
            getattr(ep, 'Indicador', None),
            getattr(ep, 'Data', None),
            getattr(ep, 'Media', None),
            getattr(ep, 'Mediana', None),
            getattr(ep, 'DataReferencia', None),
            getattr(ep, 'baseCalculo', None),
        )
        .collect()
    )
    return ipca_expec

In [21]:
dados_expectativas_focus()

       Indicador       Data DataReferencia   Media  Mediana  baseCalculo
0           IPCA 2024-08-16        08/2026  0.1631   0.1750            0
1           IPCA 2024-08-16        07/2026  0.1953   0.1947            0
2           IPCA 2024-08-16        06/2026  0.2120   0.2000            0
3           IPCA 2024-08-16        05/2026  0.2593   0.2500            0
4           IPCA 2024-08-16        04/2026  0.3387   0.3300            0
...          ...        ...            ...     ...      ...          ...
103328      IPCA 2000-01-05        04/2000  0.6100   0.6000            0
103329      IPCA 2000-01-04        05/2000  0.6000   0.5500            0
103330      IPCA 2000-01-04        04/2000  0.6000   0.6000            0
103331      IPCA 2000-01-03        05/2000  0.6100   0.5800            0
103332      IPCA 2000-01-03        04/2000  0.6000   0.6000            0

[103333 rows x 6 columns]